### ISSUE TITLE
Subnet, VPC, region values are hardcoded in Makefile

### ISSUE THREAD

**Issue by atharvs** [aws-samples/amazon-eks-custom-amis#14]
While updating the region, VPC, Subnet values under variables in amazon-eks-node-centos7.json I still get an error due to hardcoded values of Subnet, VPC and region in Makefile. 

Once I updated the correct values in Makefile, it went through

**Comment by arhea** [comment]
@atharvs you can override the default values by passing the variable names into the`make` command.

```bash
make VPC_ID=<value> SUBNET_ID=<value> AWS_REGION=<region> build-centos7-1.18
```
