### ISSUE TITLE
auditd doesn't start

### ISSUE THREAD

**Issue by mifisignal** [aws-samples/amazon-eks-custom-amis#15]
Looks like some sort of file permission issue:

```
sh-4.2# journalctl -lu auditd
-- Logs begin at Wed 2020-11-25 23:23:18 UTC, end at Thu 2020-11-26 18:09:57 UTC. --
Nov 25 23:23:26 localhost systemd[1]: Starting Security Auditing Service...
Nov 25 23:23:26 localhost auditd[575]: Could not open dir /var/log/audit (Permission denied)
Nov 25 23:23:26 localhost auditd[575]: The audit daemon is exiting.
Nov 25 23:23:26 localhost systemd[1]: auditd.service: control process exited, code=exited status=6
Nov 25 23:23:26 localhost systemd[1]: Failed to start Security Auditing Service.
Nov 25 23:23:26 localhost systemd[1]: Unit auditd.service entered failed state.
Nov 25 23:23:26 localhost systemd[1]: auditd.service failed.
```

This is for the CentOS 7 build.

**Comment by mifisignal** [comment]
`restorecon /var/log/audit/` seems to fix the problem. Suggest ensuring that all subdirectories that were relocated to separate filesystems be audited to ensure that the SELinux labels are reapplied.

**Comment by drmaciej** [comment]
@arhea I may be wrong here, but it looks like that fix doesn't do the trick for AL2.

Actually, the https://github.com/aws-samples/amazon-eks-custom-amis/blob/main/scripts/al2/cis-benchmark.sh file doesn't enable SELinux, so the workaround is never needed.

I have extended this code to enable SELinux, but `boilerplate.sh` runs before `cis-benchmark.sh`, so `selinuxenabled` is `false` at time when `migrate_and_mount_disk` is executed.

Now I reckon I will reboot one more time, after `cleanup.sh`, and add one more file to run `restorecon`.
