### ISSUE TITLE
selinuxenabled not defined

### ISSUE THREAD

**Issue by yongzhang** [aws-samples/amazon-eks-custom-amis#17]
Hi, 

Looks like `selinuxenabled` is not defined:
https://github.com/aws-samples/amazon-eks-custom-amis/blob/main/files/functions.sh#L150

**Comment by arhea** [comment]
@yongzhang - thanks for filing an issue. Can you provide the operating system and version you are hitting this issue with?

**Comment by yongzhang** [comment]
> @yongzhang - thanks for filing an issue. Can you provide the operating system and version you are hitting this issue with?

I'm using ubuntu18.04, I think the function `func selinuxenabled()` should be added somewhere.

**Comment by arhea** [comment]
@yongzhang I believe the issue happens because SELinux is not installed on Ubuntu as Ubuntu uses AppArmor. This command failing shouldn't stop the build. In fact, that command failing triggers the proper behavior which prevents enabling SELinux in Docker.
