### ISSUE TITLE
is `cni_plugin_version` needed ?

### ISSUE THREAD

**Issue by tvalasek** [aws-samples/amazon-eks-custom-amis#27]
EKS installs its own version of AWS CNI and uses that for worker nodes (daemonset). See the table with addons versions https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html

What is `cni_plugin_version` for then? It refers to the https://github.com/containernetworking/plugins/releases

Thanks for any input

**Comment by arhea** [comment]
I may get some of these terms wrong. But in general, the AWS CNI is a driver that integrates VPC with K8s. The K8s CNI Plugin is the glue between.
