### ISSUE TITLE
Build fails with "amazon-ebs: cp: cannot stat ‘/var/lib/docker/*’: No such file or directory"

### ISSUE THREAD

**Issue by JJinMaine** [aws-samples/amazon-eks-custom-amis#36]
**What happened**:

When attempting to build a custom AMI with either of the two most recent 1.19 AMI images:

amazon-eks-node-1.19-v20210720
amazon-eks-node-1.19-v20210716

I get the following error when the "migrate_and_mount_disk /dev/nvme2n1p5" step happens:

amazon-ebs: + '[' -d /var/lib/docker ']'
amazon-ebs: + mkdir -p /mnt/var/lib/docker
amazon-ebs: + mount /dev/nvme2n1p5 /mnt/var/lib/docker
amazon-ebs: + cp -Rax '/var/lib/docker/*' /mnt/var/lib/docker
amazon-ebs: cp: cannot stat ‘/var/lib/docker/*’: No such file or directory
==> amazon-ebs: Provisioning step had errors: Running the cleanup provisioner, if present...

**What you expected to happen**:

I expected the step to look something similar to this:

amazon-ebs: + '[' -d /var/lib/docker ']'
amazon-ebs: + mkdir -p /mnt/var/lib/docker
amazon-ebs: + mount /dev/nvme2n1p5 /mnt/var/lib/docker
amazon-ebs: + cp -Rax /var/lib/docker/builder /var/lib/docker/buildkit /var/lib/docker/containers /var/lib/docker/image /var/lib/docker/network /var/lib/docker/overlay2 /var/lib/docker/plugins /var/lib/docker/runtimes /var/lib/docker/swarm /var/lib/docker/tmp /var/lib/docker/trust /var/lib/docker/volumes /mnt/var/lib/docker
amazon-ebs: + mv /var/lib/docker /var/lib/docker-old
amazon-ebs: + umount /dev/nvme2n1p5

**How to reproduce it (as minimally and precisely as possible)**:

Try and build a new custom EKS AMI image that attempts to use the most recent AMI release.

**Anything else we need to know?**:

This most recent version where things still build and work normally is amazon-eks-node-1.19-v20210628

I feel like this has something to do with the following notice that is on the last two AMI releases where this is failing:

Containerd runtime support
The EKS Optimized Amazon Linux 2 AMI now contains a bootstrap (https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh) flag --container-runtime to optionally enable the containerd runtime. This flag is available in all supported Kubernetes versions of the AMI. This change is to get ahead of the removal of Docker as a supported runtime in Kubernetes (more details here (https://kubernetes.io/blog/2020/12/02/dockershim-faq/)). Feedback is appreciated.

Can anyone advise a quick fix to resolve this? Thanks!

**Environment**:
- OS: RHEL
- OS Version: 7.9
- EKS Version: 1.19
- Packer Version: 1.6.4

**Comment by drmaciej** [comment]
Same issue here - that's because of the new support for containerd. The docker daemon is now started as part of `boostrap.sh`, done here: https://github.com/awslabs/amazon-eks-ami/pull/698/files.

I think I'll just start docker before partitioning takes place, then stop it again, so `bootstrap.sh` can do its work without issues.

**Comment by drmaciej** [comment]
https://github.com/aws-samples/amazon-eks-custom-amis/blob/main/scripts/shared/cis-docker.sh#L23 will also fail, if docker is not running. I myself don't care much, so I've just disabled this particular item.

**Comment by JJinMaine** [comment]
Thanks for confirming @drmaciej! 

Do you think the general idea is that I'll need to add a line to boilerplate.sh like somewhere before:

> echo "ensure secondary disk is mounted to proper locations"
> partition_disks /dev/nvme2n1

And call _/etc/eks/bootstrap.sh --container-runtime dockerd_ ? The idea being that will we need to get all the /var/lib/docker pieces in place so that the following partitioning steps will continue as normal?

Thanks!

**Comment by drmaciej** [comment]
@JJinMaine no worries!

What I did is add `systemctl start docker` before `partition_disks` is called, and add `systemctl stop docker` before the final `reboot`. also, I've commented out `docker version`. This way, once you start docker, the files in /var/lib/docker are created and later moved to the right partition (done by `partition_disks`). That then kicks in after the reboot.

there's no need to add any extra parameters to the bootstrap script, `dockerd` is the default as per https://github.com/awslabs/amazon-eks-ami/pull/698/files#diff-049390d14bc3ea2d7882ff0f108e2802ad9b043336c5fa637e93581d9a7fdfc2R29. `bootstrap.sh` can and should be called from user data, not from Packer - I would imagine you don't want your Packer instance to try and join an EKS cluster :)

**Comment by JJinMaine** [comment]
Thanks @drmaciej, you're right. It just wasn't clear to me as to what the next steps were but what you've said makes sense. I'll give that a try this morning and see how it goes. Cheers!

**Comment by drmaciej** [comment]
glad I could help! good luck :)

**Comment by JJinMaine** [comment]
Hi @drmaciej, everything worked great! I think the only difference is that instead of commenting out the "docker version" part in cis-docker.sh I replaced it with "yum -y update docker" just to make sure I have the most recent version. Thanks again!
