### ISSUE TITLE
Support ARM64 in Ubuntu Focal

### ISSUE THREAD

**Issue by pavan-tri** [aws-samples/amazon-eks-custom-amis#38]
**What would you like to be added**:
Support for ARM64 in Ubuntu images

**Why is this needed**:
With the rise of usage of Graviton processors Ubuntu images for ARM is required.

**Comment by carlosbravoa** [comment]
As a side note, Canonical already provides ARM64 Ubuntu EKS optimized images
https://cloud-images.ubuntu.com/docs/aws/eks/
