### ISSUE TITLE
Fix the AMI's are not able to connect to the EKS cluster

### ISSUE THREAD

**Issue by dushevadnqka** [aws-samples/amazon-eks-custom-amis#39]
**What happened**:

The AMI's generated by this repo are not able to be assigned to the EKS cluster due to there is significant change in "awslabs/amazon-eks-ami" - bootstrap.sh script in particular - which is dependancy for this project: https://github.com/dushevadnqka/amazon-eks-custom-amis/blob/main/scripts/shared/eks.sh#L138.
The change could be reviewed here: https://github.com/awslabs/amazon-eks-ami/commit/af6a02dec0171bae7a20605e1427ba4d9e051bc2#diff-049390d14bc3ea2d7882ff0f108e2802ad9b043336c5fa637e93581d9a7fdfc2

**What you expected to happen**:

The AMI's generated to be able to assign to the EKS cluster

**How to reproduce it (as minimally and precisely as possible)**:

Just try do make an AMI for any of the possible OS's

**Anything else we need to know?**:

I am going to offer a PR with detailed desc of what I achieved to mitigate in case we put this great work in well status again!

**Environment**:
- OS: All
- OS Version: All
- EKS Version: All
- Packer Version: All

**Comment by bryantbiggs** [comment]
this should be resolved now - please feel free to open a new issue if encountering any issues with nodes joining the cluster
