### ISSUE TITLE
there is no  build-ubuntu2004-1.21 

### ISSUE THREAD

**Issue by zhrawj** [aws-samples/amazon-eks-custom-amis#46]
there is no  build-ubuntu2004-1.21 
there is no  build-ubuntu2004-1.21 
there is no  build-ubuntu2004-1.21 

but amazon-eks-ami have .  please Provide official support ！！！

**Comment by jayasai470** [comment]
+1 for RHEL8-1.21

**Comment by carlosbravoa** [comment]
This won't solve the request, but in case it helps, Canonical already provides Ubuntu EKS optimized images up to 1.21
https://cloud-images.ubuntu.com/docs/aws/eks/
