### ISSUE TITLE
3.15 docker.sock permissions - how does this apply to containerd?

### ISSUE THREAD

**Issue by voidlily** [aws-samples/amazon-eks-custom-amis#61]
https://github.com/aws-samples/amazon-eks-custom-amis/blob/0975b6edd0300d577da993b4d5bc795e23ba5b87/scripts/cis-docker.sh#L103

I didn't see this script making any changes to the containerd socket. Do any containerd steps need to be added like exist for the docker socket's permissions here, or does containerd socket have stricter defaults than docker on permissions?

**Comment by bryantbiggs** [comment]
resolved in #71
