### ISSUE TITLE
Ubuntu build fails on partitions due to disk name referring to root volume

### ISSUE THREAD

**Issue by dindurthy** [aws-samples/amazon-eks-custom-amis#7]
Got stuck on this for a bit. Running packer on the ubuntu images yields these errors:

```
amazon-ebs: TASK [common : be sure the new partitions are mounted via /etc/fstab] **********
    amazon-ebs: changed: [default] => (item={'delta': '0:00:00.012245', 'end': '2020-10-20 18:20:17.570817', 'stderr': '', 'cmd': 'blkid "/dev/nvme1n1p1" -sUUID -ovalue', 'stdout': '4abbc350-b74d-4038-9e87-d2adad0a4daa', 'rc': 0, 'start': '2020-10-20 18:20:17.558572', 'invocation': {'module_args': {'removes': None, '_uses_shell': True, 'chdir': None, 'stdin_add_newline': True, 'warn': False, '_raw_params': 'blkid "/dev/nvme1n1p1" -sUUID -ovalue', 'creates': None, 'strip_empty_ends': True, 'stdin': None, 'executable': '/bin/bash', 'argv': None}}, 'changed': True, 'stdout_lines': ['4abbc350-b74d-4038-9e87-d2adad0a4daa'], 'stderr_lines': [], 'failed': False, 'item': {'name': 'debian-var', 'path': '/var', 'tmp': '/srv/var', 'part_start': '0%', 'part_end': '20%'}, 'ansible_loop_var': 'item', 'item_index': 0, 'ansible_index_var': 'item_index'})
```

Looks like the ubuntu ansible config references the [root volume](https://github.com/aws-samples/amazon-eks-custom-amis/blob/b7edff30ef74c76c98cfde72f4401d11de963da2/ansible/roles/common/tasks/ubuntu.yml#L9). This [is](https://github.com/aws-samples/amazon-eks-custom-amis/blob/b7edff30ef74c76c98cfde72f4401d11de963da2/ansible/roles/common/tasks/centos.yml#L9) [inconsistent](https://github.com/aws-samples/amazon-eks-custom-amis/blob/b7edff30ef74c76c98cfde72f4401d11de963da2/ansible/roles/common/tasks/debian.yml#L9) with all of the other platform configs.

**Comment by arhea** [comment]
We have released version v2.0-beta which fixes this issue. This fixes the name of the device in the `boilerplate.sh` script.

- [function call with disk name](https://github.com/aws-samples/amazon-eks-custom-amis/blob/main/scripts/ubuntu1804/boilerplate.sh#L41) with `/dev/nvme1n1`
- [disks partitions with parted](https://github.com/aws-samples/amazon-eks-custom-amis/blob/main/files/functions.sh#L144-L168)
