### ISSUE TITLE
issue while ubuntu image creation

### ISSUE THREAD

**Issue by btrx-rkazi** [aws-samples/amazon-eks-custom-amis#9]
amazon-ebs: TASK [common : be sure the disk is partitioned according to our configuration] ***
    amazon-ebs: failed: [default] (item={u'tmp': u'/srv/var', u'path': u'/var', u'part_end': u'20%', u'part_start': u'0%', u'name': u'debian-var'}) => {"ansible_index_var": "item_index", "ansible_loop_var": "item", "changed": false, "err": "Error: Partition(s) on /dev/nvme0n1 are being used.\n", "item": {"name": "debian-var", "part_end": "20%", "part_start": "0%", "path": "/var", "tmp": "/srv/var"}, "item_index": 0, "msg": "Error while running parted script: /sbin/parted -s -m -a optimal /dev/nvme0n1 -- unit KiB mklabel gpt", "out": "", "rc": 1}
    amazon-ebs: failed: [default] (item={u'tmp': u'/srv/varlogaudit', u'path': u'/var/log/audit', u'part_end': u'30%', u'part_start': u'20%', u'name': u'debian-var-log-audit'}) => {"ansible_index_var": "item_index", "ansible_loop_var": "item", "changed": false, "err": "Error: Partition(s) on /dev/nvme0n1 are being used.\n", "item": {"name": "debian-var-log-audit", "part_end": "30%", "part_start": "20%", "path": "/var/log/audit", "tmp": "/srv/varlogaudit"}, "item_index": 1, "msg": "Error while running parted script: /sbin/parted -s -m -a optimal /dev/nvme0n1 -- unit KiB mklabel gpt mkpart primary 20% 30%", "out": "", "rc": 1}
    amazon-ebs: failed: [default] (item={u'tmp': u'/srv/home', u'path': u'/home', u'part_end': u'40%', u'part_start': u'30%', u'name': u'debian-home'}) => {"ansible_index_var": "item_index", "ansible_loop_var": "item", "changed": false, "err": "Error: Partition(s) on /dev/nvme0n1 are being used.\n", "item": {"name": "debian-home", "part_end": "40%", "part_start": "30%", "path": "/home", "tmp": "/srv/home"}, "item_index": 2, "msg": "Error while running parted script: /sbin/parted -s -m -a optimal /dev/nvme0n1 -- unit KiB mklabel gpt mkpart primary 30% 40%", "out": "", "rc": 1}
    amazon-ebs: failed: [default] (item={u'tmp': u'/srv/tmp', u'path': u'/tmp', u'part_end': u'50%', u'part_start': u'40%', u'name': u'debian-tmp'}) => {"ansible_index_var": "item_index", "ansible_loop_var": "item", "changed": false, "err": "Error: Partition(s) on /dev/nvme0n1 are being used.\n", "item": {"name": "debian-tmp", "part_end": "50%", "part_start": "40%", "path": "/tmp", "tmp": "/srv/tmp"}, "item_index": 3, "msg": "Error while running parted script: /sbin/parted -s -m -a optimal /dev/nvme0n1 -- unit KiB mklabel gpt mkpart primary 40% 50%", "out": "", "rc": 1}
    amazon-ebs: failed: [default] (item={u'tmp': u'/srv/varlibdocker', u'path': u'/var/lib/docker', u'part_end': u'90%', u'part_start': u'50%', u'name': u'docker-var-lib'}) => {"ansible_index_var": "item_index", "ansible_loop_var": "item", "changed": false, "err": "Error: Partition(s) on /dev/nvme0n1 are being used.\n", "item": {"name": "docker-var-lib", "part_end": "90%", "part_start": "50%", "path": "/var/lib/docker", "tmp": "/srv/varlibdocker"}, "item_index": 4, "msg": "Error while running parted script: /sbin/parted -s -m -a optimal /dev/nvme0n1 -- unit KiB mklabel gpt mkpart primary 50% 90%", "out": "", "rc": 1}

**Comment by arhea** [comment]
Thanks for the feedback! We will be addressing this issue in version 2 release shortly.

**Comment by arhea** [comment]
This should be addressed now:

```bash
make build-ubuntu1804-1.18
```
